import { db } from "../src/db/client.ts";
const n = await db.user.count();
console.log("users:", n);
const u = await db.user.create({ data: { email: `smoke-${Date.now()}@example.com`, name: "Smoke", passwordHash: "x", profile: { create: { displayName: "Smoke" } }, careerProfile: { create: {} }, subscription: { create: { planId: "free", provider: "none" } } } });
const r = await db.resume.create({ data: { userId: u.id, title: "Test resume", document: { version: 1, meta: { templateId: "ats-classic" } } as never } });
const got = await db.resume.findUnique({ where: { id: r.id } });
console.log("resume doc ok:", (got?.document as { title?: string }) !== null, "title:", got?.title);
await db.resume.delete({ where: { id: r.id } });
await db.user.delete({ where: { id: u.id } });
console.log("DB ADAPTER SMOKE OK");
