import { db } from "../src/db/client.ts";
import { emptyResumeDocument } from "../src/lib/resume/document.ts";
import { blankItem } from "../src/features/resume/editor-model.ts";
import { saveResumeDocument } from "../src/features/resume/repository.ts";
import { createResume } from "../src/features/resume/service.ts";

const user = await db.user.findFirst({ where: { email: { startsWith: "e2e-" } } });
const ctx = { userId: user!.id, email: user!.email, profileId: (await db.careerProfile.findFirst({ where: { userId: user!.id } }))!.id, isPremium: false, ip: "127.0.0.1" } as never;
const { resumeId } = await createResume(ctx, "DBG");
const doc = emptyResumeDocument("DBG");
doc.contact.email = "d@d.test";
doc.contact.fullName = "D Bg";
const it = blankItem("experience", "EXPERIENCE") as any;
it.employer = "Acme"; it.title = "Engineer"; it.bullets = ["Shipped a thing"];
const expSec = doc.sections.find((s) => s.kind === "EXPERIENCE")!;
expSec.items = [it];
const res = await saveResumeDocument(user!.id, resumeId, doc, { mode: "manual", label: "DBG import", source: "IMPORT" as never, createVersion: true });
console.log("save result:", { versionCreated: res.versionCreated, idMapKeys: Object.keys(res.idMap ?? {}).length });
const rows = await db.resumeSection.findMany({ where: { resumeId }, include: { items: true } });
console.log("sections:", rows.length, "items:", rows.reduce((a: number, s: any) => a + s.items.length, 0));
console.log("exp row item:", JSON.stringify(rows.find((s: any) => s.kind === "EXPERIENCE")?.items[0] ?? null).slice(0, 200));
const version = await db.resumeVersion.findFirst({ where: { resumeId }, orderBy: { createdAt: "desc" }, select: { source: true } });
console.log("version source:", version?.source);
const libRows = await db.experience.findMany({ where: { careerProfileId: ctx.profileId }, select: { employer: true } });
console.log("library experiences:", JSON.stringify(libRows));
