#!/usr/bin/env node
/**
 * Offline migration generator — the no-native-engine equivalent of
 * `prisma migrate dev`.
 *
 * How it works:
 *   1. `prisma migrate diff` (WASM schema engine) compares the current
 *      schema.prisma against a stored snapshot of the previously migrated
 *      schema (prisma/.offline-snapshot.prisma) and emits SQL.
 *   2. Writes `prisma/migrations/<timestamp>_<name>/migration.sql`.
 *   3. Applies it with scripts/db-apply-sql.mjs (records `_prisma_migrations`).
 *   4. Re-runs `prisma generate` and refreshes the snapshot.
 *
 * This produces genuine Prisma migration folders — repos created this way
 * work unchanged with `prisma migrate deploy` once on a normal machine.
 *
 *   npm run db:offline -- add_jobs_table      (or: node scripts/db-offline.mjs name)
 */
import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync, readFileSync, existsSync, copyFileSync } from "node:fs";
import { join } from "node:path";

const name = (process.argv[2] || "changes").replace(/[^a-zA-Z0-9_-]+/g, "_");

for (const file of [".env", ".env.local"]) {
  if (!existsSync(file)) continue;
  for (const line of readFileSync(file, "utf8").split("\n")) {
    const m = /^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/.exec(line);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
}

const env = { ...process.env };
// With PRISMA_OFFLINE the CLI's engine download step is satisfied by
// placeholders while the WASM schema engine does the real work.
if (env.PRISMA_OFFLINE !== "0") {
  env.PRISMA_OFFLINE = "1";
  if (!env.PRISMA_QUERY_ENGINE_LIBRARY) env.PRISMA_QUERY_ENGINE_LIBRARY = process.execPath;
  if (!env.PRISMA_SCHEMA_ENGINE_BINARY) env.PRISMA_SCHEMA_ENGINE_BINARY = process.execPath;
}

function prisma(args, opts = {}) {
  return spawnSync("npx", ["prisma", ...args], {
    stdio: ["ignore", opts.stdout === "pipe" ? "pipe" : "inherit", "pipe"],
    env,
    encoding: "utf8",
    ...opts.spawn,
  });
}

const dir = "prisma/migrations";
mkdirSync(dir, { recursive: true });
const lock = join(dir, "migration_lock.toml");
if (!existsSync(lock)) {
  writeFileSync(lock, '# Please do not edit this file manually\n# It should be added in your version-control system (e.g. Git)\nprovider = "postgresql"\n');
}

const schemaPath = "prisma/schema.prisma";
const snapshotPath = join("prisma", ".offline-snapshot.prisma");

const from = existsSync(snapshotPath) ? ["--from-schema-datamodel", snapshotPath] : ["--from-empty"];
let r = prisma(
  ["migrate", "diff", ...from, "--to-schema-datamodel", schemaPath, "--script"],
  { stdout: "pipe" },
);
if (r.status !== 0) {
  console.error((r.stderr || "") + (r.stdout || ""));
  process.exit(1);
}
const sql = (r.stdout || "").trim();
if (!sql || /empty migration/i.test(sql)) {
  console.log("No schema changes since last offline migration — nothing to do.");
  process.exit(0);
}
const stamp = new Date().toISOString().slice(0, 10).replace(/-/g, "") + "000000";
let folder = join(dir, `${stamp}_${name}`);
let i = 0;
while (existsSync(folder)) folder = join(dir, `${stamp}_${name}_${++i}`);
mkdirSync(folder, { recursive: true });
writeFileSync(join(folder, "migration.sql"), sql + "\n");
console.log(`created ${folder} (${sql.split("\n").length} lines)`);

const apply = spawnSync(process.execPath, ["scripts/db-apply-sql.mjs"], { stdio: "inherit", env });
if (apply.status !== 0) process.exit(apply.status ?? 1);

const gen = prisma(["generate"]);
if (gen.status !== 0) {
  console.error((gen.stderr || "").slice(0, 2000));
  process.exit(1);
}
copyFileSync(schemaPath, snapshotPath);
console.log("prisma client regenerated; offline snapshot updated");
